# Generated by Django 2.0 on 2018-01-15 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.FilePathField(max_length=200),
        ),
    ]
