# Generated by Django 2.0 on 2018-01-15 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180115_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.FilePathField(),
        ),
    ]
