# Generated by Django 2.0 on 2018-01-22 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180115_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='singer',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
